const state={csrf:"",view:"overview",data:null,endSessionId:""};
const titles={overview:["今日运行","运营总览"],users:["账号与身份","用户"],families:["可信关系","亲属关系"],sessions:["从请求到结束","协助会话"],diagnostics:["服务质量","问题诊断"],audit:["管理员行为","管理审计"]};
const phaseNames={idle:"空闲",waiting_family_acceptance:"等待家属接受",waiting_elder_acceptance:"等待长辈确认",waiting_screen_permission:"等待屏幕授权",active:"协助中",ended:"已结束"};
const endNames={elder_ended:"长辈结束",family_ended:"家属结束",elder_disconnected:"共享中断",admin_ended:"管理员结束"};
document.getElementById("loginForm").addEventListener("submit",login);
document.getElementById("navigation").addEventListener("click",e=>{const b=e.target.closest("button[data-view]");if(b)switchView(b.dataset.view)});
document.getElementById("refreshButton").addEventListener("click",()=>loadView());
document.getElementById("logoutButton").addEventListener("click",logout);
document.getElementById("endForm").addEventListener("submit",submitEnd);
boot();

async function boot(){try{const me=await api("/admin/api/me");showApp(me)}catch(_){showLogin()}}
async function login(event){event.preventDefault();const form=new FormData(event.currentTarget);const error=document.getElementById("loginError");error.hidden=true;try{const result=await api("/admin/api/login",{method:"POST",body:{username:form.get("username"),password:form.get("password")}});showApp(result)}catch(e){error.textContent=e.status===429?"尝试次数过多，请稍后再试。":"账号或密码不正确。";error.hidden=false}}
function showApp(result){state.csrf=result.csrf;document.getElementById("adminName").textContent=result.user.username;document.getElementById("loginView").hidden=true;document.getElementById("appView").hidden=false;loadView()}
function showLogin(){document.getElementById("appView").hidden=true;document.getElementById("loginView").hidden=false}
async function logout(){try{await api("/admin/api/logout",{method:"POST",body:{}})}finally{state.csrf="";showLogin()}}
function switchView(view){state.view=view;document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view));const [eye,title]=titles[view];document.getElementById("pageEyebrow").textContent=eye;document.getElementById("pageTitle").textContent=title;loadView()}
async function loadView(){const content=document.getElementById("content");content.innerHTML='<div class="empty">正在读取数据…</div>';try{const path=state.view==="overview"?"dashboard":state.view;state.data=await api(`/admin/api/${path}`);render();document.getElementById("refreshTime").textContent=`更新于 ${new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})}`}catch(e){if(e.status===401){showLogin();return}content.innerHTML='<div class="empty">数据暂时无法读取，请刷新重试。</div>'}}
function render(){({overview:renderOverview,users:()=>renderTablePage("users"),families:()=>renderTablePage("families"),sessions:()=>renderTablePage("sessions"),diagnostics:renderDiagnostics,audit:renderAudit}[state.view])()}
function renderOverview(){const d=state.data,m=d.metrics;document.getElementById("content").innerHTML=`<div class="metrics">${metric("注册用户",m.users,`今日 +${m.newUsersToday}`)}${metric("亲属关系",m.relationships,`${m.families} 个家庭`)}${metric("进行中协助",m.activeSessions,m.activeSessions?"需持续关注":"当前平稳")}${metric("近 7 日崩溃",m.crashes7d,m.crashes7d?"进入诊断查看":"未收到异常")}</div><div class="section-grid"><div class="stack"><section class="panel"><div class="panel-heading"><div><h2>协助链路</h2><p>近 7 日从共享开始到正常结束</p></div></div>${funnel(d.funnel)}</section><section class="panel"><div class="panel-heading"><div><h2>正在进行</h2><p>屏幕共享与当次授权状态</p></div></div>${sessionTable(d.activeSessions,true)}</section></div><div class="stack"><section class="panel"><div class="panel-heading"><div><h2>连接质量</h2><p>近 7 日会话指标</p></div></div><div class="quality-list"><div><strong>${d.quality.completionRate}%</strong><span>结束记录率</span></div><div><strong>${d.quality.signalingRate}%</strong><span>WebRTC 信令率</span></div><div><strong>${d.quality.timeoutRate}%</strong><span>异常中断率</span></div></div></section><section class="panel"><div class="panel-heading"><div><h2>需要关注</h2><p>服务与会话异常</p></div></div>${alerts(d.alerts)}</section></div></div>`;bindEndButtons()}
function metric(label,value,note){return `<div class="metric"><span>${label}</span><strong>${value}</strong><em>${note}</em></div>`}
function funnel(items){const max=Math.max(1,...items.map(i=>i.value));return `<div class="funnel">${items.map(i=>`<div class="funnel-row"><span>${i.label}</span><div class="funnel-track"><div class="funnel-fill" style="width:${Math.round(i.value/max*100)}%"></div></div><strong>${i.value}</strong></div>`).join("")}</div>`}
function alerts(items){return items.length?`<div class="alerts">${items.map(i=>`<div class="alert ${i.severity}"><strong>${escapeHtml(i.title)}</strong><span>${escapeHtml(i.detail)}</span></div>`).join("")}</div>`:'<div class="empty">当前没有需要处置的异常。</div>'}
function renderTablePage(type){const configs={users:{placeholder:"搜索昵称、脱敏手机号或身份",render:userTable},families:{placeholder:"搜索长辈、家属或家庭编号",render:familyTable},sessions:{placeholder:"搜索会话、长辈或家属",render:items=>sessionTable(items,true)}};const c=configs[type];document.getElementById("content").innerHTML=`<div class="toolbar"><input id="tableSearch" class="search-input" placeholder="${c.placeholder}" aria-label="搜索"></div><div id="tableResult">${c.render(state.data.items)}</div>`;document.getElementById("tableSearch").addEventListener("input",debounce(async e=>{const q=encodeURIComponent(e.target.value);state.data=await api(`/admin/api/${type}?q=${q}`);document.getElementById("tableResult").innerHTML=c.render(state.data.items);bindEndButtons()},250));bindEndButtons()}
function userTable(items){return table(["用户","手机号","身份","注册时间","最后登录"],items.map(i=>[escapeHtml(i.name),i.phone,roleName(i.role),date(i.createdAt),date(i.lastLoginAt)]))}
function familyTable(items){return table(["家庭编号","长辈","已绑定家属","当前状态","最后更新"],items.map(i=>[`<span class="mono">${i.id}</span>`,escapeHtml(i.elderName),escapeHtml(i.relativeNames||`暂无（${i.relativeCount}）`),status(phaseNames[i.phase]||i.phase,i.active?"active":""),date(i.updatedAt)]))}
function sessionTable(items,actions){return table(["会话","长辈 / 家属","状态","开始时间","结束结果",...(actions?["操作"]:[])],items.map(i=>[`<span class="mono">${escapeHtml(i.id.slice(0,12))}</span>`,`<strong>${escapeHtml(i.elderName)}</strong><br><span class="muted">${escapeHtml(i.helperName)}</span>`,status(phaseNames[i.phase]||i.phase,i.status==="active"?"active":""),date(i.startedAt),i.endReason?escapeHtml(endNames[i.endReason]||i.endReason):"—",...(actions?[i.status==="active"?`<button class="table-action end-session" data-id="${encodeURIComponent(i.id)}">结束会话</button>`:"—"]:[])]))}
function renderDiagnostics(){const d=state.data;document.getElementById("content").innerHTML=`<div class="stack"><section class="panel"><div class="panel-heading"><div><h2>服务状态</h2><p>当前 relay 进程的运行边界</p></div></div><div class="health-grid">${health("服务",d.health.storageReady?"正常":"初始化中")}${health("持久化",d.health.postgres?"PostgreSQL":"本地文件")}${health("TURN",d.health.turnConfigured?"已配置":"未配置")}${health("运行时间",duration(d.health.uptimeSeconds))}</div></section><section class="panel"><div class="panel-heading"><div><h2>异常提醒</h2><p>按影响程度排列</p></div></div>${alerts(d.alerts)}</section><section class="panel"><div class="panel-heading"><div><h2>崩溃报告</h2><p>仅显示设备与错误摘要，不包含屏幕画面</p></div></div>${d.crashes.length?`<div class="stack">${d.crashes.map(c=>`<article class="crash-card"><header><strong>${escapeHtml(c.message||"未知错误")}</strong><time>${date(c.createdAt)}</time></header><p>${escapeHtml(c.role||"未知身份")} · ${escapeHtml(c.device||"未知设备")} · ${escapeHtml(c.appVersion||"未知版本")}</p></article>`).join("")}</div>`:'<div class="empty">尚未收到崩溃报告。</div>'}</section></div>`}
function renderAudit(){const items=state.data.items;document.getElementById("content").innerHTML=table(["时间","管理员","操作","来源","详情"],items.map(i=>[date(i.createdAt),escapeHtml(i.actor),auditName(i.type),escapeHtml(i.remote),`<span class="mono">${escapeHtml(JSON.stringify(i.detail))}</span>`]))}
function table(headers,rows){if(!rows.length)return '<div class="empty">当前没有可展示的记录。</div>';return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c??"—"}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function status(text,kind=""){return `<span class="status ${kind}">${escapeHtml(text)}</span>`}function health(a,b){return `<div class="health-item"><span>${a}</span><strong>${b}</strong></div>`}function roleName(r){return r==="elder"?"长辈":r==="family"?"家属":"未选择"}function auditName(t){return {login_failed:"登录失败",login_succeeded:"登录成功",logout:"退出登录",session_force_ended:"紧急结束会话"}[t]||t}
function bindEndButtons(){document.querySelectorAll(".end-session").forEach(b=>b.addEventListener("click",()=>{state.endSessionId=b.dataset.id;document.getElementById("endReason").value="";document.getElementById("endDialog").showModal()}))}
async function submitEnd(e){e.preventDefault();if(e.submitter&&e.submitter.value==="cancel"){document.getElementById("endDialog").close();return}const reason=document.getElementById("endReason").value.trim();if(reason.length<4)return;try{await api(`/admin/api/sessions/${state.endSessionId}/end`,{method:"POST",body:{reason}});document.getElementById("endDialog").close();showNotice("会话已结束，双方状态将同步刷新。");loadView()}catch(_){showNotice("会话未能结束，可能已由用户关闭。")}}
function showNotice(text){const n=document.getElementById("notice");n.textContent=text;n.hidden=false;setTimeout(()=>n.hidden=true,5000)}
async function api(path,options={}){const init={method:options.method||"GET",credentials:"same-origin",headers:{}};if(options.body){init.headers["Content-Type"]="application/json";init.body=JSON.stringify(options.body)}if(init.method!=="GET"&&state.csrf)init.headers["X-Admin-CSRF"]=state.csrf;const response=await fetch(path,init);let body={};try{body=await response.json()}catch(_){}if(!response.ok){const error=new Error(body.error||"request failed");error.status=response.status;throw error}return body}
function date(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleString("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"})}function duration(s){if(s<60)return`${Math.round(s)} 秒`;if(s<3600)return`${Math.round(s/60)} 分钟`;return`${Math.round(s/3600)} 小时`}function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function debounce(fn,ms){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}
